// MUNDARI SAMAJ DATABASE
// This file is automatically generated by the Admin Panel.

const MUNDARI_DB = {
  "mundari_hero_title": "Welcome to Mundari Samaj",
  "mundari_hero_desc": "Preserving our Culture, Language, and Heritage.",
  "mundari_hero_images": [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Munda_people_dance.jpg/1200px-Munda_people_dance.jpg"
  ],
  "mundari_history_list": [], 
  "mundari_video_list": [],
  "mundari_gallery_list": [],
  "mundari_about_text": "We are dedicated to preserving the rich culture, language, and traditions of the Munda community."
};
